### PR TITLE
Updated year in license file

### PR DESCRIPTION
**Pull request by jobinsjohn**

### CODE REVIEW

**Review by hemangshah — COMMENTED** [review]
Hi @jobinsjohn, why it is required to change the year in the license?

**Comment by hemangshah** [comment]
Closed this for now until will not hear from the PR author.

**Comment by jobinsjohn** [comment]
Its always better to update year in license file. Thats why i suggested the edit. But the sole discretion to accept or reject the suggestion is on the owner of the repository.

**Comment by hemangshah** [comment]
@jobinsjohn, thanks! You can read [this](https://softwareengineering.stackexchange.com/questions/210472/is-renewal-of-mit-license-needed-on-github-at-the-beginning-of-each-year) to have more information on the same.

**Pull request merged**
